### ISSUE TITLE
能对复杂模型进行存储吗？

### ISSUE THREAD

**Issue by GitBaoChao** [544523660/LKFMDB#2]
就是模型套模型的情况，比如老师模型里有学生模型...

**Comment by HectorLiuk** [comment]
不支持你所说的模型套模型。你所说的是联表查询，此项目支持联表。你可以换种模式去实现，把学生当做外键你可以试试`LKDBColumnDes`。

**Comment by sven820** [comment]
联合主键的表好像不支持吧！
